---

- hosts: all
  tasks:
  - name: Force unregister before register
    redhat_subscription:
      state: absent
    ignore_errors: true

  - name: register node with subscription-manager
    redhat_subscription: state=present username="{{ rhn_user_name }}" password="{{ rhn_password }}" autosubscribe=false
    register: task_result
    until: task_result | succeeded
    retries: 10
    delay: 5

  - name: attach node to subscription pool
    command: subscription-manager register --pool {{ pool_id }}
    register: task_result
    until: task_result.rc == 0
    retries: 10
    delay: 1
    ignore_errors: no

  - name: attach node to subscription pool
    command: subscription-manager attach --pool {{ pool_id }}
    register: task_result
    until: task_result.rc == 0
    retries: 10
    delay: 1
    ignore_errors: no

  - name: Enable only required repositories with Subscription Manager
    command: subscription-manager repos --disable="*" --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.4-rpms"

  - name: Run yum update
    yum: name=* state=latest

  - name: "Install pre-requisite packages"
    yum: state=present name={{ item }}
    with_items:
    - wget
    - vim-enhanced
    - net-tools
    - bind-utils
    - git
    - iptables
    - bridge-utils 
    - atomic-openshift-utils
