---

- name: launching an ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: find a subnet id
    ec2_vpc_subnet_facts:
      region: "{{aws_region}}"
    register: subnet_ids

  - name: create a security group
    ec2_group:
      name: allow_all
      description: "allow all traffic"
      region: "{{aws_region}}"
      vpc_id: "{{vpc_id}}"
      rules:
        - proto: tcp
          from_port: 0
          to_port: 60000
          cidr_ip: 0.0.0.0/0
    register: ocp_security_group

  - name: launch an ec2 instance
    ec2:
      instance_type: m4.large
      region: "{{aws_region}}"
      image: "{{ami_id}}"
      vpc_subnet_id: "{{vpc_subnet_id}}"
      group_id: "{{ocp_security_group.group_id}}"
      key_name: "{{key_name}}"
      assign_public_ip: true
      wait: True
      volumes:
        - device_name: /dev/sda1
          volume_size: 50
          volume_type: gp2
        - device_name: /dev/sdb
          volume_size: 20
          volume_type: gp2
      instance_tags:
        Name: "{{ instance_name }}"
        ocp_master: "{{ ocp_master }}"
        ocp_node: "{{ ocp_node }}"
        ocp_new_node: "{{ ocp_new_node }}"
        ocp_etcd: "{{ ocp_etcd }}"
        ready_for_provisionning: "True"
    register: ec2

  - name: connect to Tower
    command: "tower-cli config {{ item }}"
    with_items:
      - username {{ tower_user }}
      - password {{ tower_password }}
      - host {{ tower_host }} 
    delegate_to: localhost 

  - name: create host in Tower debug
    debug: 
       var: ec2.instances 
       verbosity: 0

  - name: create host in Tower
    command: "tower-cli host create -n {{ec2.instances[0].public_ip}} -i 7"

  - name: associate host to master group in Tower
    command: "tower-cli host associate --host {{ item.public_ip }} --group 357"
    with_items: ec2.instances
    when:
     - ocp_master == True

  - name: associate host to nfs group in Tower
    command: "tower-cli host associate --host {{ item.public_ip }} --group 359"
    with_items: ec2.instances
    when:
     - ocp_nfs == True

  - name: associate host to etcd group in Tower
    command: "tower-cli host associate --host {{ item.public_ip }} --group 358"
    with_items: ec2.instances
    when:
     - ocp_etcd == True

  - name: associate host to node group in Tower
    command: "tower-cli host associate --host {{ item.public_ip }} --group 360"
    with_items: ec2.instances
    when:
     - ocp_node == True

  - name: associate host to new_node group in Tower
    command: "tower-cli host associate --host {{ec2.instances[0].public_ip}} --group 502"
    when:
     - ocp_new_node == True
